package process

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func PortableCredentialsDir(rootDir string) string {
	rootDir = strings.TrimSpace(rootDir)
	if rootDir == "" {
		return ""
	}
	return filepath.Join(rootDir, "data", "devdesk", "cloudflare")
}

func PortableCredentialsPath(rootDir, tunnelID string) string {
	tunnelID = strings.ToLower(strings.TrimSpace(tunnelID))
	dir := PortableCredentialsDir(rootDir)
	if dir == "" || tunnelID == "" {
		return ""
	}
	return filepath.Join(dir, tunnelID+".json")
}

// LegacyCredentialsPath remains as the compatibility entrypoint used by older
// call sites, but now resolves to MCP DevDesk's portable file location. When a
// legacy cloudflared file exists it is copied into portable storage first.
func LegacyCredentialsPath(tunnelID string) string {
	rootDir := defaultPortableRoot()
	if rootDir == "" {
		return userCloudflaredCredentialsPath(tunnelID)
	}
	if path, err := EnsurePortableCredentials(rootDir, tunnelID); err == nil {
		return path
	}
	return PortableCredentialsPath(rootDir, tunnelID)
}

func userCloudflaredCredentialsPath(tunnelID string) string {
	home := UserHomeDir()
	tunnelID = strings.ToLower(strings.TrimSpace(tunnelID))
	if home == "" || tunnelID == "" {
		return ""
	}
	return filepath.Join(home, ".cloudflared", tunnelID+".json")
}

func defaultPortableRoot() string {
	if configured := strings.TrimSpace(os.Getenv("MCP_DEVDESK_ROOT")); configured != "" {
		if absolute, err := filepath.Abs(configured); err == nil {
			return absolute
		}
	}

	candidates := make([]string, 0, 4)
	if executable, err := os.Executable(); err == nil {
		dir := filepath.Dir(executable)
		candidates = append(candidates, dir, filepath.Dir(dir))
	}
	if cwd, err := os.Getwd(); err == nil {
		candidates = append(candidates, cwd, filepath.Dir(cwd))
	}
	for _, candidate := range candidates {
		candidate = filepath.Clean(candidate)
		if info, err := os.Stat(filepath.Join(candidate, "cloudflared.exe")); err == nil && !info.IsDir() {
			return candidate
		}
	}
	if len(candidates) > 0 {
		return filepath.Clean(candidates[0])
	}
	return ""
}

// PreparePortableCredentialsCreatePath reserves a unique filename inside the
// portable Cloudflare directory and then removes the empty placeholder so
// cloudflared tunnel create can write the credentials file itself.
func PreparePortableCredentialsCreatePath() (string, error) {
	rootDir := defaultPortableRoot()
	if rootDir == "" {
		return "", errors.New("cannot determine portable Cloudflare root")
	}
	dir := PortableCredentialsDir(rootDir)
	if dir == "" {
		return "", errors.New("cannot determine portable Cloudflare directory")
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("create portable Cloudflare directory: %w", err)
	}
	file, err := os.CreateTemp(dir, ".tunnel-create-*.json")
	if err != nil {
		return "", fmt.Errorf("reserve portable Cloudflare credentials path: %w", err)
	}
	path := file.Name()
	if err := file.Close(); err != nil {
		_ = os.Remove(path)
		return "", err
	}
	if err := os.Remove(path); err != nil {
		return "", fmt.Errorf("prepare portable Cloudflare credentials path: %w", err)
	}
	return path, nil
}

// FinalizePortableCredentials renames/copies credentials generated by
// cloudflared into the stable UUID-based portable filename used at runtime.
func FinalizePortableCredentials(tunnelID, source string) (string, error) {
	rootDir := defaultPortableRoot()
	if rootDir == "" {
		return "", errors.New("cannot determine portable Cloudflare root")
	}
	return StorePortableCredentials(rootDir, tunnelID, source)
}

func EnsurePortableCredentials(rootDir, tunnelID string) (string, error) {
	dst := PortableCredentialsPath(rootDir, tunnelID)
	if dst == "" {
		return "", errors.New("cannot determine portable Cloudflare path")
	}
	if info, err := os.Stat(dst); err == nil && !info.IsDir() {
		return dst, nil
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return dst, err
	}
	src := userCloudflaredCredentialsPath(tunnelID)
	if src == "" {
		return dst, errors.New("legacy Cloudflare path is unavailable")
	}
	if err := copyPortableFile(src, dst); err != nil {
		return dst, fmt.Errorf("migrate Cloudflare tunnel file: %w", err)
	}
	return dst, nil
}

func StorePortableCredentials(rootDir, tunnelID, src string) (string, error) {
	dst := PortableCredentialsPath(rootDir, tunnelID)
	if dst == "" {
		return "", errors.New("cannot determine portable Cloudflare path")
	}
	if err := copyPortableFile(src, dst); err != nil {
		return dst, err
	}
	if filepath.Clean(src) != filepath.Clean(dst) {
		_ = os.Remove(src)
	}
	return dst, nil
}

func copyPortableFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o700); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	tmp, err := os.CreateTemp(filepath.Dir(dst), ".cloudflare-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return err
	}
	if _, err := io.Copy(tmp, in); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpName, dst); err != nil {
		if _, statErr := os.Stat(dst); statErr == nil {
			return nil
		}
		return err
	}
	return nil
}
